=== Energinet-DataHub/ARCHIVED-geh-charges/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/Schemas/urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:sawsdl="http://www.w3.org/ns/sawsdl" xmlns:cimp="http://www.iec.ch/cimprofile" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ediel.org:structure:requestchangeofpricelist:0:1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="urn:entsoe.eu:wgedi:codelists" schemaLocation="urn-entsoe-eu-wgedi-codelists.xsd"/>
	<xs:element name="RequestChangeOfPriceList_MarketDocument" type="cim:RequestChangeOfPriceList_MarketDocument"/>
	<xs:complexType name="ChargeGroup" sawsdl:modelReference="http://iec.ch/TC57/CIM101#ChargeGroup">
		<xs:sequence>
			<xs:element name="ChargeType" type="cim:ChargeType" minOccurs="1" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#ChargeGroup.ChargeType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="PartyID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:simpleContent>
			<xs:extension base="cim:PartyID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="ChargeKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:ChargeTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="VATPayerKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:VATPayerTypeList"/>
	</xs:simpleType>
	<xs:complexType name="ChargeType" sawsdl:modelReference="http://iec.ch/TC57/CIM101#ChargeType">
		<xs:sequence>
			<xs:element name="chargeTypeOwner_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="type" type="cim:ChargeKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.type"/>
            <xs:element name="process.processOperationType" type="cim:ChargeKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.type"/>
            <xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.name"/>
			<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.description"/>
			<xs:element name="priceTimeFrame_Period.resolution" type="xs:duration" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.resolution"/>
			<xs:element name="effectiveDate" type="xs:dateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#ChargeType.effectiveDate"/>
			<xs:element name="terminationDate" type="xs:dateTime" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#ChargeType.terminationDate"/>
			<xs:element name="VATPayer" type="cim:VATPayerKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DK_ChargeType.VATPayer"/>
			<xs:element name="transparentInvoicing" type="xs:boolean" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DK_ChargeType.transparentInvoicing"/>
			<xs:element name="taxIndicator" type="xs:boolean" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DK_ChargeType.taxIndicator"/>
			<xs:element name="Series_Period" type="cim:Series_Period" minOccurs="0" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#ChargeType.Series_Period"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MktActivityRecord" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MktActivityRecord">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="businessProcessReference_MktActivityRecord.mRID" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="ChargeGroup" type="cim:ChargeGroup" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MktActivityRecord.ChargeGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Position_Integer" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Integer">
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="999999"/>
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Amount_Decimal" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Decimal">
		<xs:restriction base="xs:decimal">
			<xs:totalDigits value="17"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Point" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Point">
		<xs:sequence>
			<xs:element name="position" type="cim:Position_Integer" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Point.position"/>
			<xs:element name="price.amount" type="cim:Amount_Decimal" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Price.amount"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="MessageKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:MessageTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="ProcessKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:ProcessTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="BusinessSectorKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:BusinessSectorTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="MarketRoleKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:RoleTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="ESMP_DateTime" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTime">
		<xs:restriction base="xs:dateTime">
			<xs:pattern value="((([0-9]{4})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])Z)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="RequestChangeOfPriceList_MarketDocument" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="type" type="cim:MessageKind_String" default="D10" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.type"/>
			<xs:element name="process.processType" type="cim:ProcessKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Process.processType"/>
            <xs:element name="businessSector.type" type="cim:BusinessSectorKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#BusinessSector.type"/>
			<xs:element name="sender_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="sender_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type"/>
			<xs:element name="receiver_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="receiver_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type"/>
			<xs:element name="createdDateTime" type="cim:ESMP_DateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.createdDateTime"/>
			<xs:element name="MktActivityRecord" type="cim:MktActivityRecord" minOccurs="1" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument.MktActivityRecord"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="YMDHM_DateTime" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTime">
		<xs:restriction base="xs:string">
			<xs:pattern value="((([0-9]{4})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ESMP_DateTimeInterval" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTimeInterval">
		<xs:sequence>
			<xs:element name="start" type="cim:YMDHM_DateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTimeInterval.start"/>
			<xs:element name="end" type="cim:YMDHM_DateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTimeInterval.end"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Series_Period" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period">
		<xs:sequence>
			<xs:element name="resolution" type="xs:duration" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.resolution"/>
			<xs:element name="timeInterval" type="cim:ESMP_DateTimeInterval" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.timeInterval"/>
			<xs:element name="Point" type="cim:Point" minOccurs="1" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.Point"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Energinet-DataHub/ARCHIVED-geh-charges/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/BundleMixOfChargeMasterDataOperations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 Energinet DataHub A/S

Licensed under the Apache License, Version 2.0 (the "License2");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
    <cim:mRID>DocIdSomeDocID</cim:mRID>
    <cim:type>D10</cim:type>
    <cim:process.processType>D18</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-04-06T09:30:47Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>Operation1</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>Charge001</cim:mRID>
                <cim:name>TARIFF 1 NAME 1</cim:name>
                <cim:description>The tariff 1 description</cim:description>
                <cim:priceTimeFrame_Period.resolution>P1D</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>2022-10-31T23:00:00Z</cim:effectiveDate>
                <cim:VATPayer>D01</cim:VATPayer>
                <cim:transparentInvoicing>false</cim:transparentInvoicing>
                <cim:taxIndicator>false</cim:taxIndicator>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
    <cim:MktActivityRecord>
        <cim:mRID>Operation2</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>Tariff002</cim:mRID>
                <cim:name>Charge Tariff 2 Name</cim:name>
                <cim:description>The tariff 2 description</cim:description>
                <cim:priceTimeFrame_Period.resolution>P1D</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>2022-11-30T23:00:00Z</cim:effectiveDate>
                <cim:VATPayer>D02</cim:VATPayer>
                <cim:transparentInvoicing>true</cim:transparentInvoicing>
                <cim:taxIndicator>false</cim:taxIndicator>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
    <cim:MktActivityRecord>
        <cim:mRID>Operation3</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D02</cim:type>
                <cim:mRID>Charge001</cim:mRID>
                <cim:name>FEE 1 NAME 1</cim:name>
                <cim:description>The fee 1 description</cim:description>
                <cim:priceTimeFrame_Period.resolution>P1M</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>2022-12-31T23:00:00Z</cim:effectiveDate>
                <cim:VATPayer>D01</cim:VATPayer>
                <cim:transparentInvoicing>false</cim:transparentInvoicing>
                <cim:taxIndicator>false</cim:taxIndicator>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
    <cim:MktActivityRecord>
        <cim:mRID>Operation4</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>Charge001</cim:mRID>
                <cim:name>TARIFF 1 NAME 2</cim:name>
                <cim:description>The tariff 2 description 2</cim:description>
                <cim:priceTimeFrame_Period.resolution>P1D</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>2022-12-31T23:00:00Z</cim:effectiveDate>
                <cim:VATPayer>D01</cim:VATPayer>
                <cim:transparentInvoicing>false</cim:transparentInvoicing>
                <cim:taxIndicator>false</cim:taxIndicator>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>

=== Energinet-DataHub/ARCHIVED-geh-charges/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/CreateSubscriptionDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 Energinet DataHub A/S

Licensed under the Apache License, Version 2.0 (the "License2");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
    <cim:mRID>DocId{{$isoTimestamp}}</cim:mRID>
    <cim:type>D10</cim:type>
    <cim:process.processType>D18</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">{{GridAccessProvider}}</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>{{$isoTimestamp}}</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>SysTestOpId{{$isoTimestamp}}</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">{{GridAccessProvider}}</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D01</cim:type>
                <cim:mRID>{{$randomCharacters}}</cim:mRID>
                <cim:name>Charge Sub Name</cim:name>
                <cim:description>The charge subscription description</cim:description>
                <cim:priceTimeFrame_Period.resolution>P1M</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>{{$isoTimestampPlusOneMonth}}</cim:effectiveDate>
                <cim:VATPayer>D01</cim:VATPayer>
                <cim:transparentInvoicing>false</cim:transparentInvoicing>
                <cim:taxIndicator>false</cim:taxIndicator>
                <cim:Series_Period>
                    <cim:resolution>P1M</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>{{$YMDHM_TimestampPlusOneMonth}}</cim:start>
                        <cim:end>{{$YMDHM_TimestampPlusOneMonth}}</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>200.001</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>

=== Energinet-DataHub/ARCHIVED-geh-charges/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/PriceSeries/SubscriptionPriceSeries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 Energinet DataHub A/S

Licensed under the Apache License, Version 2.0 (the "License2");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
    <cim:mRID>DocId{{$isoTimestamp}}</cim:mRID>
    <cim:type>D10</cim:type>
    <cim:process.processType>D08</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">{{$senderMarketParticipant}}</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>{{$isoTimestamp}}</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>TestOpId{{$isoTimestamp}}</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">{{$senderMarketParticipant}}</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D01</cim:type>
                <cim:mRID>TestSub</cim:mRID>
                <cim:effectiveDate>{{$NextYear}}-05-31T22:00:00Z</cim:effectiveDate>
                <cim:Series_Period>
                    <cim:resolution>P1M</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>{{$NextYear}}-05-31T22:00Z</cim:start>
                        <cim:end>{{$NextYear}}-06-30T22:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>200.001</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>
